---
title: "NBirthPoisson"
author: "Amy Racine"
date: "20 12 2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

To model the no of birth before lockdown to estimate the change in no. of birth post lockdown
```{r Nbirth}
 
library(ggplot2)
# read in data
PortionEst<-function(Tlockdown)
{  
datain<-read.csv2("./NbirthCheck.csv")
 datain<-data.frame(datain)
 # fake output
 write.csv2(datain,"./outNbirthCheck.csv")
 
# total observation months
Tend<-length(datain[,2])
Tlockdown_1<-Tlockdown-1
# time start lockdown in month
   
# create season as a factor for evaluation
time<-datain[,1] 
time_2<-datain[,1]^2
season<-as.factor(datain[,4])
all<-data.frame(datain[,1:3],time_2 )
 colnames(all)<-c("time","PTB.rate","nbirth","time_2")
  
all1<-all
# use prelockdown birth to forecast post lockdown birth 
all1[Tlockdown_1:Tend,3]<-NA
 
gg1<-ggplot(data=all,aes(x=time,y=nbirth)) +geom_point()+ggtitle("no of birth")
print(gg1)
 
model1<-glm(data=all1, nbirth~-1+season+time+time_2,family=poisson)
 print("Poisson Model,polynomial , before lockdown with season and polynomial trend effect")
 #print(summary(model1))
w<-predict(model1,newdata=all,type="response")

w_pred<-w[Tlockdown:Tend] 
 
Portion<-mean(all[Tlockdown_1:Tend,3])/mean(w_pred)

# portion of prelockdown birth 
 print("portion of no of birth before lockdown")
 print(Portion)
}


PortionEst(276)
 
```
